### PR TITLE
Remove GitHub Assessments feature

### LINKED ISSUE #2838: Remove Github Classroom feature
This feature hasn't been used at all since its inception and is currently not working.

Screenshot 2024-03-12 at 6 06 07 PM

I propose that we remove it, to cut away dead wood. (We'll keep the wiki pages in case someone wants to revive this.)

### PR DESCRIPTION
**Pull request by RichDom2185**
### Description

Closes #2838.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

File: src/commons/application/types/SessionTypes.ts [hunk 1]
```diff
@@ -118,7 +117,6 @@ export type SessionState = {
   readonly gradings: Map<number, GradingQuery>;
   readonly notifications: Notification[];
   readonly googleUser?: string;
-  readonly githubAssessment?: MissionRepoData;
   readonly githubOctokitObject: { octokit: Octokit | undefined };
```
Comment (RichDom2185) [inline src/commons/application/types/SessionTypes.ts:120]: I'm leaving this object here just in case the folders team would require it (to minimise conflicts); but if it turns out to not be needed then it can be removed in the future.

File: src/commons/sagas/GitHubPersistenceSaga.ts [hunk 2]
```diff
@@ -58,11 +58,6 @@ function* githubLoginSaga() {
...
 
 function* githubLogoutSaga() {
-  if (store.getState() && store.getState().workspaces.githubAssessment.hasUnsavedChanges) {
-    yield call(showWarningMessage, 'You have unsaved changes!', 2000);
-    return;
-  }
-
   yield put(actions.removeGitHubOctokitObjectAndAccessToken());
   yield call(showSuccessMessage, `Logged out from GitHub`, 1000);
 }
```
Comment (RichDom2185) [inline src/commons/sagas/GitHubPersistenceSaga.ts:63]: Ditto, I'll keep these sagas just in case (leaving them in won't break anything), but we can remove in the future if the folders team do not require them.

File: src/routes/routerConfig.tsx [hunk 3]
```diff
@@ -15,18 +14,17 @@ import Constants from '../commons/utils/Constants';
...
-    return redirect(redirectTo);
-  }
-  return returnValue ?? null;
-};
+// const conditionalLoader = (condition: boolean, redirectTo: string, returnValue?: any) => () => {
+//   if (condition) {
+//     return redirect(redirectTo);
+//   }
+//   return returnValue ?? null;
+// };
```
Comment (RichDom2185) [inline src/routes/routerConfig.tsx:22]: Kept for future refactoring purposes.

**Review by martin-henz — APPROVED** [review]
Looks good!
