### PR TITLE
Make the retrieval of breakpoint line numbers more robust

### LINKED ISSUE #2362: Breakpoints in the playground editor not restored properly from localstorage
Steps to replicate:
1. Go to the playground.
1. Set a breakpoint.
1. Refresh the page.
1. All lines up to the line with the greatest line number that had a breakpoint added will have breakpoints set.

Most likely broken by #2356.

### PR DESCRIPTION
**Pull request by ianyong**
### Description

The JSON-serialised representation of the breakpoints array in the localstorage is unable to distinguish between empty slots, and slots where the value is `null`. As a result, after serialising into JSON and deserialising back to JavaScript, the empty slots of an array are now filled with `null`. This breaks the invariant that only line numbers with a breakpoint are non-empty slots that was previously relied on in `getBreakpointLineNumbers`.

~~To resolve this issue, we now check that the value corresponding to the line number is the string `'ace_breakpoint'` to determine whether the line number has a breakpoint set or not.~~
To resolve this issue, we now define a breakpoint as follows:
> Breakpoints are elements in the array with the value 'ace_breakpoint' where the associated line number is the index of the element in the array.

By making use of array semantics instead of object semantics, we have a cleaner definition & implementation.

Fixes #2362.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

Follow the steps to replicate in the linked issue.

### CODE REVIEW

File: src/commons/editor/Editor.tsx [hunk 1]
```diff
@@ -149,13 +149,26 @@ const makeHandleGutterClick =
  * array has empty slots (i.e., array indices which are not defined at all). Breakpoints
  * are represented in the Ace Editor's breakpoints array as key-value pairs where the
  * key is a string representation of the line number it is on, and the value is
- * 'ace_breakpoint'. As such, to get an array of breakpoint line numbers, we need to
- * get the keys of the Ace Editor's breakpoint array/object and parse them as integers.
+ * 'ace_breakpoint'.
+ *
+ * However, because the JSON-serialised representation of empty slots in a JavaScript
+ * array is the same as that of the 'null', we cannot simply parse all keys of the object
```
Comment (martin-henz) [inline src/commons/editor/Editor.tsx:155]: Actually, accessing the value of an empty array slot results in undefined, not null. The fix is still valid I think, but the comment should change to avoid confusion.

**Review by martin-henz — CHANGES_REQUESTED** [review]

File: src/commons/editor/Editor.tsx (hunk 1 above)
Comment (ianyong) [reply src/commons/editor/Editor.tsx:155]: I was previously accessing the array as an object based on the observation that empty slots in an array don't even exist as key-value pairs in the underlying object. After thinking about it more from your comment though, I realised that since we now have to check the value of elements in the array anyway, it no longer makes sense to think in terms of object semantics when we can just make use of array semantics for a cleaner implementation. This also means that most of the comment can be removed.

Thanks for bringing this up! I'll make the change (for both code and comment).

**Review by martin-henz — APPROVED** [review]
Great.
