### PR TITLE
fix: achievements loading and assessment workspace 404

### LINKED ISSUE #160: Don't use location as variable name
It clashes with window.location, which is accessible from anywhere as a global.

### LINKED ISSUE #3072: Assessment Workspace: 404 when loading individual assessment
Despite being an individual assessment, the frontend still tries to load the team configuration for the assessment, resulting in a 404.

### PR DESCRIPTION
**Pull request by RichDom2185**
### Description

Closes #3072.

Also fixes a small bug following #3061 so that updated achievements can be redisplayed in the frontend when the backend returns with fresh data.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

File: src/commons/assessmentWorkspace/AssessmentWorkspace.tsx [hunk 1]
```diff
@@ -191,9 +191,10 @@ const AssessmentWorkspace: React.FC<AssessmentWorkspaceProps> = props => {
   }, []);
 
   useEffect(() => {
-    handleTeamOverviewFetch(props.assessmentId);
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, []);
+    if (assessmentOverview && assessmentOverview.maxTeamSize > 1) {
```
Comment (josh1248) [inline src/commons/assessmentWorkspace/AssessmentWorkspace.tsx:194]: looks like a good fix!

File: src/pages/achievement/control/AchievementControl.tsx [hunk 2]
```diff
@@ -35,18 +35,13 @@ const AchievementControl: React.FC = () => {
...
   const [initialAchievements, initialGoals] = useTypedSelector(state => [
     state.achievement.achievements,
     state.achievement.goals
   ]);
   const inferencer = useMemo(
     () => new AchievementInferencer(initialAchievements, initialGoals),
-    // We only want to create the inferencer once
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-    []
+    [initialAchievements, initialGoals]
```
Comment (josh1248) [inline src/pages/achievement/control/AchievementControl.tsx:44]: good change to enable reload of achievements.

**Review by josh1248 — APPROVED** [review]
LGTM!
